name: Continuous integration
on:
  pull_request:
  push:
    branches-ignore:
      - master
jobs:
  code_checks:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - uses: ramsey/composer-install@v3
      - name: Test code style
        run: vendor/bin/ecs
      - name: Static analysis (phpstan)
        run: vendor/bin/phpstan
      - name: Tests
        run: vendor/bin/phpunit --coverage-clover coverage.xml